version: '3.9'

services:

  woovi-challenge:
    networks:
      - woovi-bridge
    build:
      context: server
      dockerfile: Dockerfile
    hostname: woovi-challenge
    container_name: woovi-challenge
    volumes:
      - ./server:/app
    ports:
      - 4000:4000

  woovi-web:
    networks:
      - woovi-bridge
    build:
      context: web
      dockerfile: Dockerfile
    hostname: woovi-web
    container_name: woovi-web
    volumes:
      - ./web:/app/web
    ports:
      - 5173:5173
    depends_on:
      - woovi-challenge

networks:
  woovi-bridge:
    driver: bridge
